### ISSUE TITLE
Program crashes on startup

### ISSUE THREAD

**Issue by gvnfc3** [donutteam/jeffs-map-creator#7]
**Describe the bug**
When I launched the program, it showed a white screen then crashed.

**To Reproduce**
1. Launch program

**Expected behavior**
The program was meant to open and not crash.

**Screenshots**

**Game/Mod Information (please complete the following information):**
 - Version 0.1
 - Version 4 (Pure 3D Editor)

**Additional context**
[Butter.log](https://github.com/donutteam/jeffs-map-creator/files/10227558/Butter.log)

**Comment by gvnfc3** [comment]
[DxDiag.txt](https://github.com/donutteam/jeffs-map-creator/files/10298664/DxDiag.txt)
Here you go.

**Comment by TheButterApple24** [comment]
Seems like it could be related to not having a Nvidea GPU, currently looking for a fix!

**Comment by TheButterApple24** [comment]
Should be fixed in latest version

**Comment by gvnfc3** [comment]
Same thing happens, and I think you forgot to update the version.

**Comment by TheButterApple24** [comment]
Just to clarify, when you right click the .exe and go to details, does it show 0.3.0.0? 

The latest version is currently 0.3 which can be grabbed here if you haven't: https://modbakery.donutteam.com/releases/view/jeffs-map-creator

**Comment by TheButterApple24** [comment]
If there are still issues even with 0.3, I would recommomend updating your drivers (video and such) to ensure it's up to date. Otherwise it might be a different issue entirely.
